name: Test
on: 
  pull_request:
   types: [opened]

jobs: 
  test:
   runs-on: ubuntu-latest 
   steps:
     - uses: actions/checkout@v2
     - uses: ./ 
       with: 
         GITHUB_TOKEN: ${{secrets.MY_SECRET_TOKEN}}
         TENOR_TOKEN: ${{secrets.MY_SECRET_TOKEN}}